version: '3.8'
services:
  www:
    container_name: www
    build:
      context: ./www
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    restart: always
    depends_on:
      - postgres
    ports:
      - '5555:5555'
  nginx_api:
    container_name: nginx_api
    build:
      context: ./www
      dockerfile: ./infra/nginx/Dockerfile
    ports:
      - '8080:8080'
    restart: always
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'financial_db'
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./resources/sql:/docker-entrypoint-initdb.d
  web:
    container_name: 'web'
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./web:/app

volumes:
  db_data: